"""columns_gin_index

Revision ID: 6138998e2403
Revises: 1061ecca2c2b
Create Date: 2023-12-13 13:45:31.700535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6138998e2403'
down_revision: Union[str, None] = '1061ecca2c2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('quantity', sa.Integer()))
    op.execute(f'CREATE INDEX book_index ON book USING GIN(misc_data)')
    op.execute(f'CREATE INDEX patron_index ON patron USING GIN(misc_data)')
    op.execute(f'CREATE INDEX checkout_index ON checkout USING GIN(misc_data)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'quantity')
    op.drop_index(f'book_index', table_name='book')
    op.drop_index(f'patron_index', table_name='patron')
    op.drop_index(f'checkout_index', table_name='checkout')
    # ### end Alembic commands ###
